// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://25fcl6x3ljgmdg6q7dn4qzvxki.appsync-api.eu-north-1.amazonaws.com/graphql',
          region: 'eu-north-1',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-mmvrbac4f5ebbkofhnbzkksrwa'
        }
    }
};

export default config;